#!/bin/sh

set -e

lb config noauto \
	--debian-installer live \
	--linux-packages "linux-image linux-headers" \
	--debootstrap-options "--include=apt-transport-https,ca-certificates,openssl,fasttrack-archive-keyring" \
	--debootstrap-engine mmdebstrap \
	--distribution bookworm \
	--initramfs dracut-live \
	--apt-recommends false \
	--apt aptitude \
	--archive-areas "main contrib non-free non-free-firmware" \
	--chroot-localrepos "/home/user/local-repo-test" \
	--bootappend-live 'mitigations=auto,nosmt nosmt=force spectre_v2=on spectre_bhi=on spec_store_bypass_disable=on l1tf=full,force mds=full,nosmt tsx=off tsx_async_abort=full,nosmt kvm.nx_huge_pages=force l1d_flush=on mmio_stale_data=full,nosmt retbleed=auto,nosmt gather_data_sampling=force reg_file_data_sampling=on slab_nomerge slab_debug=FZ init_on_alloc=1 init_on_free=1 page_alloc.shuffle=1 pti=on randomize_kstack_offset=on vsyscall=none debugfs=off kfence.sample_interval=100 vdso32=0 amd_iommu=force_isolation intel_iommu=on iommu=force iommu.passthrough=0 iommu.strict=1 efi=disable_early_pci_dma random.trust_bootloader=off random.trust_cpu=off extra_latent_entropy loglevel=0 rd.live.overlay.overlayfs=1' \
	"${@}"

